node{

  git branch: "test", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example" 

  stage ('Build HML image') {
    sh "docker tag localhost:5000/robsonbittencourt/jenkins-pipeline-example:dsv robsonbittencourt/jenkins-pipeline-example:hml"

    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'DOCKER', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
        sh "docker login -u=${env.USERNAME} -p=${env.PASSWORD}"
    }   

    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml ;"
  }

  stage ('Ui Tests') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn verify -Pui-tests"
    }
  }

  stage ('Build PRD image') {
    sh "docker tag robsonbittencourt/jenkins-pipeline-example:hml robsonbittencourt/jenkins-pipeline-example:prd"

    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'DOCKER', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
        sh "docker login -u=${env.USERNAME} -p=${env.PASSWORD}"
    }   

    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:prd ;"
  }

}