node{

  git branch: "test", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example" 

  stage ('Build HML image') {
    sh "docker tag localhost:5000/robsonbittencourt/jenkins-pipeline-example:dsv localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml"
    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml ;"
  }

  stage ('Ui Tests') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn verify -Pui-tests"
    }

    sh 'mvn allure:report'

    echo 'Publish Allure report'
    
    publishHTML(
        target: [
            allowMissing         : false,
            alwaysLinkToLastBuild: false,
            keepAll              : true,
            reportDir            : 'target/site/allure-maven-plugin',
            reportFiles          : 'index.html',
            reportName           : "Allure Report"
        ]
    )
  }

  stage ('Build PRD image') {
    sh "docker tag localhost:5000/robsonbittencourt/jenkins-pipeline-example:hml localhost:5000/robsonbittencourt/jenkins-pipeline-example:prd"
    sh "docker push localhost:5000/robsonbittencourt/jenkins-pipeline-example:prd ;"
  }

}