node{

  git branch: "test", url: "https://github.com/robsonbittencourt/jenkins-pipeline-example" 

  stage ('Build Jar') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn package -Dmaven.test.skip=true"
    }
  }

  stage ('Ui Tests') {
    withEnv(["JAVA_HOME=${ tool "java-8" }", "PATH+MAVEN=${ tool "maven" }/bin:${env.JAVA_HOME}/bin"]) {
        sh "mvn verify -Pui-tests"
    }
  }
  
}